	.section	.rodata.map_aname.0,"aMS",@progbits,1
	.type	.L.map_aname.0, @object
.L.map_aname.0:
	.asciz	"Xamarin.AndroidX.CustomView"
	.size	.L.map_aname.0, 28

	.section	.rodata.map_aname.1,"aMS",@progbits,1
	.type	.L.map_aname.1, @object
.L.map_aname.1:
	.asciz	"Xamarin.AndroidX.AppCompat"
	.size	.L.map_aname.1, 27

	.section	.rodata.map_aname.2,"aMS",@progbits,1
	.type	.L.map_aname.2, @object
.L.map_aname.2:
	.asciz	"Xamarin.Forms.PancakeView"
	.size	.L.map_aname.2, 26

	.section	.rodata.map_aname.3,"aMS",@progbits,1
	.type	.L.map_aname.3, @object
.L.map_aname.3:
	.asciz	"Xamarin.Google.Android.Material"
	.size	.L.map_aname.3, 32

	.section	.rodata.map_aname.4,"aMS",@progbits,1
	.type	.L.map_aname.4, @object
.L.map_aname.4:
	.asciz	"Plugin.CurrentActivity"
	.size	.L.map_aname.4, 23

	.section	.rodata.map_aname.5,"aMS",@progbits,1
	.type	.L.map_aname.5, @object
.L.map_aname.5:
	.asciz	"Xamarin.AndroidX.Lifecycle.Common"
	.size	.L.map_aname.5, 34

	.section	.rodata.map_aname.6,"aMS",@progbits,1
	.type	.L.map_aname.6, @object
.L.map_aname.6:
	.asciz	"Xamarin.AndroidX.ViewPager"
	.size	.L.map_aname.6, 27

	.section	.rodata.map_aname.7,"aMS",@progbits,1
	.type	.L.map_aname.7, @object
.L.map_aname.7:
	.asciz	"Xamarin.AndroidX.SwipeRefreshLayout"
	.size	.L.map_aname.7, 36

	.section	.rodata.map_aname.8,"aMS",@progbits,1
	.type	.L.map_aname.8, @object
.L.map_aname.8:
	.asciz	"Xamarin.AndroidX.Activity"
	.size	.L.map_aname.8, 26

	.section	.rodata.map_aname.9,"aMS",@progbits,1
	.type	.L.map_aname.9, @object
.L.map_aname.9:
	.asciz	"Xamarin.AndroidX.SavedState"
	.size	.L.map_aname.9, 28

	.section	.rodata.map_aname.10,"aMS",@progbits,1
	.type	.L.map_aname.10, @object
.L.map_aname.10:
	.asciz	"Rg.Plugins.Popup"
	.size	.L.map_aname.10, 17

	.section	.rodata.map_aname.11,"aMS",@progbits,1
	.type	.L.map_aname.11, @object
.L.map_aname.11:
	.asciz	"Xamarin.AndroidX.RecyclerView"
	.size	.L.map_aname.11, 30

	.section	.rodata.map_aname.12,"aMS",@progbits,1
	.type	.L.map_aname.12, @object
.L.map_aname.12:
	.asciz	"Xamarin.AndroidX.CardView"
	.size	.L.map_aname.12, 26

	.section	.rodata.map_aname.13,"aMS",@progbits,1
	.type	.L.map_aname.13, @object
.L.map_aname.13:
	.asciz	"Syncfusion.SfRadialMenu.Android"
	.size	.L.map_aname.13, 32

	.section	.rodata.map_aname.14,"aMS",@progbits,1
	.type	.L.map_aname.14, @object
.L.map_aname.14:
	.asciz	"Xamarin.AndroidX.DrawerLayout"
	.size	.L.map_aname.14, 30

	.section	.rodata.map_aname.15,"aMS",@progbits,1
	.type	.L.map_aname.15, @object
.L.map_aname.15:
	.asciz	"Acr.UserDialogs"
	.size	.L.map_aname.15, 16

	.section	.rodata.map_aname.16,"aMS",@progbits,1
	.type	.L.map_aname.16, @object
.L.map_aname.16:
	.asciz	"Syncfusion.Core.XForms.Android"
	.size	.L.map_aname.16, 31

	.section	.rodata.map_aname.17,"aMS",@progbits,1
	.type	.L.map_aname.17, @object
.L.map_aname.17:
	.asciz	"Xamarin.Essentials"
	.size	.L.map_aname.17, 19

	.section	.rodata.map_aname.18,"aMS",@progbits,1
	.type	.L.map_aname.18, @object
.L.map_aname.18:
	.asciz	"Xamarin.AndroidX.Legacy.Support.Core.UI"
	.size	.L.map_aname.18, 40

	.section	.rodata.map_aname.19,"aMS",@progbits,1
	.type	.L.map_aname.19, @object
.L.map_aname.19:
	.asciz	"Syncfusion.SfRadialMenu.XForms.Android"
	.size	.L.map_aname.19, 39

	.section	.rodata.map_aname.20,"aMS",@progbits,1
	.type	.L.map_aname.20, @object
.L.map_aname.20:
	.asciz	"Xamarin.AndroidX.Core"
	.size	.L.map_aname.20, 22

	.section	.rodata.map_aname.21,"aMS",@progbits,1
	.type	.L.map_aname.21, @object
.L.map_aname.21:
	.asciz	"Xamarin.AndroidX.Lifecycle.LiveData.Core"
	.size	.L.map_aname.21, 41

	.section	.rodata.map_aname.22,"aMS",@progbits,1
	.type	.L.map_aname.22, @object
.L.map_aname.22:
	.asciz	"Xamarin.Forms.Platform.Android"
	.size	.L.map_aname.22, 31

	.section	.rodata.map_aname.23,"aMS",@progbits,1
	.type	.L.map_aname.23, @object
.L.map_aname.23:
	.asciz	"ConfiApp.Android"
	.size	.L.map_aname.23, 17

	.section	.rodata.map_aname.24,"aMS",@progbits,1
	.type	.L.map_aname.24, @object
.L.map_aname.24:
	.asciz	"AndHUD"
	.size	.L.map_aname.24, 7

	.section	.rodata.map_aname.25,"aMS",@progbits,1
	.type	.L.map_aname.25, @object
.L.map_aname.25:
	.asciz	"Plugin.LocalNotifications"
	.size	.L.map_aname.25, 26

	.section	.rodata.map_aname.26,"aMS",@progbits,1
	.type	.L.map_aname.26, @object
.L.map_aname.26:
	.asciz	"Xamarin.CommunityToolkit"
	.size	.L.map_aname.26, 25

	.section	.rodata.map_aname.27,"aMS",@progbits,1
	.type	.L.map_aname.27, @object
.L.map_aname.27:
	.asciz	"Mono.Android"
	.size	.L.map_aname.27, 13

	.section	.rodata.map_aname.28,"aMS",@progbits,1
	.type	.L.map_aname.28, @object
.L.map_aname.28:
	.asciz	"FormsViewGroup"
	.size	.L.map_aname.28, 15

	.section	.rodata.map_aname.29,"aMS",@progbits,1
	.type	.L.map_aname.29, @object
.L.map_aname.29:
	.asciz	"Xamarin.AndroidX.Loader"
	.size	.L.map_aname.29, 24

	.section	.rodata.map_aname.30,"aMS",@progbits,1
	.type	.L.map_aname.30, @object
.L.map_aname.30:
	.asciz	"Xamarin.Google.Guava.ListenableFuture"
	.size	.L.map_aname.30, 38

	.section	.rodata.map_aname.31,"aMS",@progbits,1
	.type	.L.map_aname.31, @object
.L.map_aname.31:
	.asciz	"Xamarin.AndroidX.Lifecycle.ViewModel"
	.size	.L.map_aname.31, 37

	.section	.rodata.map_aname.32,"aMS",@progbits,1
	.type	.L.map_aname.32, @object
.L.map_aname.32:
	.asciz	"Plugin.LocalNotification"
	.size	.L.map_aname.32, 25

	.section	.rodata.map_aname.33,"aMS",@progbits,1
	.type	.L.map_aname.33, @object
.L.map_aname.33:
	.asciz	"Xamarin.AndroidX.Fragment"
	.size	.L.map_aname.33, 26

	.section	.rodata.map_aname.34,"aMS",@progbits,1
	.type	.L.map_aname.34, @object
.L.map_aname.34:
	.asciz	"Xamarin.AndroidX.CoordinatorLayout"
	.size	.L.map_aname.34, 35

	.section	.rodata.map_aname.35,"aMS",@progbits,1
	.type	.L.map_aname.35, @object
.L.map_aname.35:
	.asciz	"Xamarin.AndroidX.VersionedParcelable"
	.size	.L.map_aname.35, 37

	.section	.rodata.map_aname.36,"aMS",@progbits,1
	.type	.L.map_aname.36, @object
.L.map_aname.36:
	.asciz	"Xamarin.AndroidX.AppCompat.AppCompatResources"
	.size	.L.map_aname.36, 46

